import { GameData } from './types';

export const DEFAULT_DATA: GameData = {
  technologies: [
    { id: 'spark', name: 'Apache Spark', type: 'Compute (Batch/Streaming)', bestFor: ['batch_etl','ml_batch','stream_etl','delta_lakehouse'], rationale: 'General cluster compute for ETL, MLlib, SQL, and Structured Streaming.', tags:['compute','sql','ml']},
    { id: 'flink', name: 'Apache Flink', type: 'Streaming Compute', bestFor: ['low_latency','exactly_once','complex_event'], rationale: 'Low-latency, stateful stream processing with exactly-once.', tags:['stream']},
    { id: 'kafka', name: 'Apache Kafka', type: 'Event Streaming / Log', bestFor: ['event_bus','log_aggregation','replay','stream_etl'], rationale: 'Durable distributed log for pub/sub and decoupling producers/consumers.', tags:['stream','messaging']},
    { id: 'pulsar', name: 'Apache Pulsar', type: 'Event Streaming', bestFor: ['event_bus','geo_replication','queue_topics'], rationale: 'Multi-tenant streaming with queues + topics, geo-replication.', tags:['stream']},
    { id: 'schema_registry', name: 'Schema Registry', type: 'Governance', bestFor: ['schema_evolution','producer_consumer_contracts'], rationale: 'Controls Avro/JSON/Protobuf schemas for compatibility across services.', tags:['governance']},
    { id: 'hdfs', name: 'HDFS', type: 'Distributed Filesystem', bestFor: ['data_lake','cheap_storage'], rationale: 'Distributed file storage for on-prem big data clusters.', tags:['storage']},
    { id: 's3', name: 'Amazon S3 (or GCS/ADLS)', type: 'Object Storage', bestFor: ['data_lake','cheap_storage','bronze_zone'], rationale: 'Cheap, durable object storage for data lakes.', tags:['storage','cloud']},
    { id: 'delta', name: 'Delta Lake', type: 'Lakehouse Table Format', bestFor: ['delta_lakehouse','acid_on_lake','time_travel'], rationale: 'ACID tables, time travel and schema enforcement on data lake.', tags:['table-format']},
    { id: 'iceberg', name: 'Apache Iceberg', type: 'Table Format', bestFor: ['acid_on_lake','bi_sql','large_partitions'], rationale: 'High-performance table format with hidden partitioning.', tags:['table-format']},
    { id: 'hudi', name: 'Apache Hudi', type: 'Table Format', bestFor: ['cdc','upserts_on_lake'], rationale: 'Upserts and incremental pulls on data lakes.', tags:['table-format']},
    { id: 'trino', name: 'Trino (Presto)', type: 'Distributed SQL', bestFor: ['ad_hoc_sql','bi_sql'], rationale: 'Massively parallel SQL engine across diverse sources.', tags:['sql']},
    { id: 'hive', name: 'Hive / Spark SQL', type: 'SQL on Files', bestFor: ['ad_hoc_sql','bi_sql'], rationale: 'SQL over Parquet/ORC tables with metastore.', tags:['sql']},
    { id: 'druid', name: 'Apache Druid', type: 'Real-time OLAP', bestFor: ['subsecond_olap','stream_olap','rollups'], rationale: 'Columnar analytics w/ ingestion from streams and batch.', tags:['olap']},
    { id: 'pinot', name: 'Apache Pinot', type: 'Real-time OLAP', bestFor: ['subsecond_olap','user_facing_analytics'], rationale: 'OLAP for user-facing analytics and dashboards with low latency.', tags:['olap']},
    { id: 'clickhouse', name: 'ClickHouse', type: 'OLAP DBMS', bestFor: ['subsecond_olap','log_analytics'], rationale: 'Blazing-fast columnar database for logs and analytics.', tags:['olap']},
    { id: 'cassandra', name: 'Apache Cassandra', type: 'NoSQL Wide-Column', bestFor: ['hot_kv','timeseries_write'], rationale: 'Write-heavy, geo-distributed KV/time-series store.', tags:['nosql']},
    { id: 'mongodb', name: 'MongoDB', type: 'NoSQL Document', bestFor: ['json_docs','app_backends'], rationale: 'Flexible JSON documents; secondary indexes and aggregations.', tags:['nosql']},
    { id: 'redis', name: 'Redis', type: 'In-memory KV / Cache', bestFor: ['caching','leaderboards','realtime_features'], rationale: 'In-memory data structures for speed-critical paths.', tags:['cache']},
    { id: 'elasticsearch', name: 'Elasticsearch / OpenSearch', type: 'Search & Logs', bestFor: ['search','log_analytics','observability'], rationale: 'Full-text search and log analytics with Kibana/Grafana.', tags:['search','logs']},
    { id: 'airflow', name: 'Apache Airflow', type: 'Orchestration', bestFor: ['orchestrate','scheduler','lineage_hooks'], rationale: 'DAG-based scheduling and orchestration for ETL/ML.', tags:['orchestration']},
    { id: 'dagster', name: 'Dagster', type: 'Orchestration', bestFor: ['orchestrate','data_quality','software_defined_assets'], rationale: 'Modern orchestrator with data assets and observability.', tags:['orchestration']},
    { id: 'dbt', name: 'dbt', type: 'Transform (ELT)', bestFor: ['warehouse_sql','bi_sql','tests_docs'], rationale: 'SQL-first transformations with tests and docs in warehouses.', tags:['elt']},
    { id: 'beam', name: 'Apache Beam', type: 'Unified API', bestFor: ['portable_pipelines','batch_streaming'], rationale: 'Portable pipelines executed on Flink/Spark/Dataflow.', tags:['api']},
    { id: 'nifi', name: 'Apache NiFi', type: 'Dataflow / Ingest', bestFor: ['dragdrop_ingest','edge_ingest'], rationale: 'Visual flow-based ingest with back pressure and provenance.', tags:['ingest']},
    { id: 'storm', name: 'Apache Storm', type: 'Stream Compute', bestFor: ['low_latency'], rationale: 'Legacy stream processing for very low latency.', tags:['stream']},
    { id: 'ray', name: 'Ray', type: 'Distributed Compute', bestFor: ['ml_training','python_scale'], rationale: 'Distributed Python for ML, RL, and serving.', tags:['compute','ml']},
    { id: 'feature_store', name: 'Feature Store (Feast)', type: 'ML Ops', bestFor: ['ml_features','online_offline'], rationale: 'Manages online/offline features for ML consistency.', tags:['mlops']},
    { id: 'superset', name: 'Apache Superset', type: 'BI / Dashboards', bestFor: ['bi_dashboards'], rationale: 'Open-source BI for dashboards over SQL sources.', tags:['bi']},
    { id: 'great_expectations', name: 'Great Expectations', type: 'Data Quality', bestFor: ['data_quality'], rationale: 'Declarative tests to validate data.', tags:['quality']},
    { id: 'k8s', name: 'Kubernetes', type: 'Orchestration (Infra)', bestFor: ['scaling_platform'], rationale: 'Scales services/operators for data workloads.', tags:['infra']},
    { id: 'snowflake', name: 'Snowflake', type: 'Cloud DW', bestFor: ['warehouse_sql','bi_sql'], rationale: 'Elastic cloud data warehouse.', tags:['cloud','dw']},
    { id: 'bigquery', name: 'BigQuery', type: 'Cloud DW', bestFor: ['warehouse_sql','bi_sql','serverless_sql'], rationale: 'Serverless MPP SQL warehouse.', tags:['cloud','dw']},
    { id: 'redshift', name: 'Amazon Redshift', type: 'Cloud DW', bestFor: ['warehouse_sql','bi_sql'], rationale: 'Cloud data warehouse on AWS.', tags:['cloud','dw']},
    { id: 'databricks', name: 'Databricks', type: 'Lakehouse Platform', bestFor: ['delta_lakehouse','ml_batch','mlops'], rationale: 'Managed Spark + Delta with ML tooling.', tags:['platform']},
    { id: 'glue', name: 'AWS Glue', type: 'Serverless ETL', bestFor: ['batch_etl','catalog'], rationale: 'Serverless Spark ETL and Data Catalog.', tags:['cloud']},
    { id: 'dataflow', name: 'Google Dataflow', type: 'Managed Beam', bestFor: ['stream_etl','batch_etl'], rationale: 'Managed Beam for stream/batch on GCP.', tags:['cloud']},
    { id: 'kinesis', name: 'Amazon Kinesis', type: 'Managed Streams', bestFor: ['event_bus','stream_etl'], rationale: 'Managed streaming on AWS.', tags:['cloud']},
    { id: 'pubsub', name: 'Google Pub/Sub', type: 'Managed PubSub', bestFor: ['event_bus','stream_etl'], rationale: 'Pub/sub messaging on GCP.', tags:['cloud']}
  ],
  useCases: [
    { id: 'batch_etl', text: 'Nightly batch ETL over TBs into curated tables', tags:['etl'], difficulty:'easy' },
    { id: 'ml_batch', text: 'Offline ML training on historical data', tags:['ml'], difficulty:'medium' },
    { id: 'stream_etl', text: 'Stream ETL with windowed aggregations', tags:['stream'], difficulty:'medium' },
    { id: 'low_latency', text: 'Sub-100ms processing latency', tags:['latency'], difficulty:'hard' },
    { id: 'exactly_once', text: 'Exactly-once stateful stream processing', tags:['stream'], difficulty:'hard' },
    { id: 'complex_event', text: 'Complex event processing (CEP) with patterns', tags:['stream'], difficulty:'hard' },
    { id: 'event_bus', text: 'Decouple microservices via durable event bus', tags:['messaging'], difficulty:'easy' },
    { id: 'log_aggregation', text: 'Ingest & search logs at massive scale', tags:['logs'], difficulty:'medium' },
    { id: 'replay', text: 'Replay and reprocess historical events', tags:['stream'], difficulty:'medium' },
    { id: 'data_lake', text: 'Store raw data (bronze) cheaply and durably', tags:['storage'], difficulty:'easy' },
    { id: 'cheap_storage', text: 'Archive large cold data cost-effectively', tags:['storage'], difficulty:'easy' },
    { id: 'delta_lakehouse', text: 'Lakehouse with ACID, time-travel tables', tags:['lakehouse'], difficulty:'medium' },
    { id: 'acid_on_lake', text: 'ACID transactions & schema enforcement on lake', tags:['lakehouse'], difficulty:'hard' },
    { id: 'time_travel', text: 'Query historical snapshots of tables', tags:['lakehouse'], difficulty:'medium' },
    { id: 'upserts_on_lake', text: 'Efficient upserts/CDC on lake tables', tags:['cdc'], difficulty:'hard' },
    { id: 'cdc', text: 'Change Data Capture from OLTP to analytics', tags:['cdc'], difficulty:'hard' },
    { id: 'ad_hoc_sql', text: 'Ad-hoc federated SQL across many sources', tags:['sql'], difficulty:'medium' },
    { id: 'bi_sql', text: 'BI dashboards over curated warehouse tables', tags:['bi'], difficulty:'easy' },
    { id: 'stream_olap', text: 'Real-time ingestion + sub-second OLAP', tags:['olap'], difficulty:'hard' },
    { id: 'subsecond_olap', text: 'User-facing <500ms analytics at scale', tags:['olap'], difficulty:'hard' },
    { id: 'rollups', text: 'Rollups & indexing for efficient analytics', tags:['olap'], difficulty:'medium' },
    { id: 'timeseries_write', text: 'High write-rate time-series (IoT)', tags:['timeseries'], difficulty:'hard' },
    { id: 'hot_kv', text: 'Low-latency KV for hot path', tags:['kv'], difficulty:'medium' },
    { id: 'json_docs', text: 'Flexible JSON document store for apps', tags:['nosql'], difficulty:'easy' },
    { id: 'app_backends', text: 'Operational app backend datastore', tags:['nosql'], difficulty:'easy' },
    { id: 'caching', text: 'Caching and acceleration layer', tags:['cache'], difficulty:'easy' },
    { id: 'leaderboards', text: 'Sorted sets/leaderboards & counters', tags:['realtime'], difficulty:'medium' },
    { id: 'realtime_features', text: 'Online features for ML inference', tags:['mlops'], difficulty:'hard' },
    { id: 'search', text: 'Full-text search over documents/events', tags:['search'], difficulty:'medium' },
    { id: 'observability', text: 'Logs/metrics/traces observability stack', tags:['logs'], difficulty:'medium' },
    { id: 'orchestrate', text: 'Schedule and monitor pipelines (DAGs)', tags:['orchestration'], difficulty:'easy' },
    { id: 'scheduler', text: 'Cron + dependency management across jobs', tags:['orchestration'], difficulty:'easy' },
    { id: 'lineage_hooks', text: 'Track lineage/metadata and data assets', tags:['governance'], difficulty:'medium' },
    { id: 'data_quality', text: 'Validate quality rules & contracts', tags:['quality'], difficulty:'medium' },
    { id: 'warehouse_sql', text: 'Cloud data warehouse SQL/ELT', tags:['dw'], difficulty:'easy' },
    { id: 'tests_docs', text: 'Transformations with tests and docs', tags:['elt'], difficulty:'easy' },
    { id: 'ml_training', text: 'Distributed ML training & tuning', tags:['ml'], difficulty:'hard' },
    { id: 'ml_features', text: 'Manage online/offline ML features', tags:['mlops'], difficulty:'hard' },
    { id: 'online_offline', text: 'Consistency between online/offline features', tags:['mlops'], difficulty:'hard' },
    { id: 'bi_dashboards', text: 'Self-service BI dashboards', tags:['bi'], difficulty:'easy' },
    { id: 'dragdrop_ingest', text: 'Visual drag-and-drop ingest flows', tags:['ingest'], difficulty:'easy' },
    { id: 'edge_ingest', text: 'Edge & site-level ingest with backpressure', tags:['ingest'], difficulty:'medium' },
    { id: 'producer_consumer_contracts', text: 'Contracts between producers/consumers', tags:['governance'], difficulty:'medium' },
    { id: 'schema_evolution', text: 'Evolve schemas safely with compat rules', tags:['governance'], difficulty:'medium' },
    { id: 'geo_replication', text: 'Replicate data across regions', tags:['resilience'], difficulty:'hard' },
    { id: 'queue_topics', text: 'Queueing & pub/sub topics pattern', tags:['messaging'], difficulty:'medium' },
    { id: 'serverless_sql', text: 'Serverless SQL analytics', tags:['dw'], difficulty:'easy' },
    { id: 'catalog', text: 'Central catalog/metastore', tags:['governance'], difficulty:'easy' },
    { id: 'scaling_platform', text: 'Scale data platform on K8s', tags:['infra'], difficulty:'hard' }
  ]
};